Translated a bunch of stuff and updated to 0910
DazedMTL/Violated-Princess pull request #3
Opened 2023-09-10 16:08 UTC by Milky00000

Updating to 0910 seems to have removed a bunch of uslesse parts, hence why wall of stuff being removed. Also adding parts to be able to load in recollection.

By the way the CommonEvents.json seems to be broken somewhere. Don't know if you ever took a look but you can't even open the menu without it crashing. Formatting the file caused it to not be able to load the menu .img and probably other stuff. I wanted to take a look by the file is so huge...

2023-09-10 18:03 UTC, dazedanon requested changes
Couple of things that need fixes. Also the menu doesn't crash at all for me. Unsure why you are seeing that on latest.\

Also can you update the system.json with the right version number when you get the chance?

2023-09-10 18:03 UTC, dazedanon commented on www/data/Map030.json
> -                            "code": 0,
Keep at 0

2023-09-10 18:03 UTC, dazedanon commented on www/data/Map030.json
> +                                "\\n<セレナ>"
TL This

2023-09-10 18:03 UTC, dazedanon commented on www/data/Map046.json
> +                                "\\n< Serena >!Goblin cave...!\nIt's like that again...! ? )"
Fix this sentence

2023-09-10 18:03 UTC, dazedanon commented on www/data/Map046.json
> +                                "………戻ろう。戻って、綺麗にしないと……。"
Fix this

2023-09-10 18:03 UTC, dazedanon commented on www/data/Map046.json
> +                            "code": 401,
Keep at 0

2023-09-12 05:19 UTC, Milky00000 commented
Trying to figure how all this work,. I put a bunch of updates but it created new commits instead of updating. I'll do a new pull request when i fixed all my stuff.

2023-09-12 05:19 UTC, closed without merging